In [1]:
import pandas as pd
import numpy as np

In [2]:

index=pd.date_range('2021',periods=12,freq='Y')
df = pd.DataFrame(index=index,columns=['revenue','EBITDA','Tax','Capital_Expenditures','Working_Capital','Cash_flow','Discount_factore','Present_Value_of_Future_Cash_Flow'],dtype='float64')
df['revenue'][0] = 222.0  
df

,revenue,EBITDA,Tax,Capital_Expenditures,Working_Capital,Cash_flow,Discount_factore,Present_Value_of_Future_Cash_Flow
2021-12-31,222.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2029-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2030-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2031-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2032-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
Growth_Factor = 1.18
Revenue=222
for year in range(1, 12):
    df['revenue'][year]= df['revenue'][year-1]*Growth_Factor
    


EBITDA=0.45
Discount_rate=0.06
Taxes = - 0.21
Capital_Expenditures = -0.03
Working_Capital_Increase =  - 0.06

for year in range(0, 12):
    df['EBITDA'][year] = df['revenue'][year]*EBITDA
    df['Discount_factore'][year] = (1-Discount_rate)**year
    df['Tax'][year]=df['EBITDA'][year]*Taxes
    df['Capital_Expenditures'][year]=df['revenue'][year]*Capital_Expenditures
    df['Working_Capital'][year]=df['revenue'][year]*Working_Capital_Increase
    df['Cash_flow'][year]= df['EBITDA'][year]+ df['Tax'][year]+ df['Capital_Expenditures'][year]+df['Working_Capital'][year]
    df['Present_Value_of_Future_Cash_Flow'][year]=df['Cash_flow'][year] * df['Discount_factore'][year]
    
df

,revenue,EBITDA,Tax,Capital_Expenditures,Working_Capital,Cash_flow,Discount_factore,Present_Value_of_Future_Cash_Flow
2021-12-31,222.000000,99.900000,-20.979000,-6.660000,-13.320000,58.941000,1.000000,58.941000
2022-12-31,261.960000,117.882000,-24.755220,-7.858800,-15.717600,69.550380,0.940000,65.377357
2023-12-31,309.112800,139.100760,-29.211160,-9.273384,-18.546768,82.069448,0.883600,72.516565
2024-12-31,364.753104,164.138897,-34.469168,-10.942593,-21.885186,96.841949,0.830584,80.435373
2025-12-31,430.408663,193.683898,-40.673619,-12.912260,-25.824520,114.273500,0.780749,89.218916
2026-12-31,507.882222,228.547000,-47.994870,-15.236467,-30.472933,134.842730,0.733904,98.961622
2027-12-31,599.301022,269.685460,-56.633947,-17.979031,-35.958061,159.114421,0.689870,109.768231
2028-12-31,707.175206,318.228843,-66.828057,-21.215256,-42.430512,187.755017,0.648478,121.754922
2029-12-31,834.466743,375.510034,-78.857107,-25.034002,-50.068005,221.550920,0.609569,135.050559
2030-12-31,984.670757,443.101841,-93.051387,-29.540123,-59.080245,261.430086,0.572995,149.798080
2031-12-31,1161.911493,522.860172,-109.800636,-34.857345,-69.714690,308.487501,0.538615,166.156031
2032-12-31,1371.055562,616.975003,-129.564751,-41.131667,-82.263334,364.015252,0.506298,184.300269